<?php
/**************************************************************************
 *
 * @file test.inc
 *
 *************************************************************************/


/**************************************************************************
 * Test API Calls here
 *************************************************************************/
function cio_test()
{
	//$account = user_load(635);
	//print_r(user_pass_reset_url($account));
	
	//exit();
	
	
	/*
	cio_track_customer('123', array(
		'email' => 'bob@bob.com',
		'created_at' => 1361205308,
		'first_name' => 'Bob',
		'last_name' => 'Bob',
		'some_value' => "I'm here",
	));
	
	
	cio_track_event('123', array(
		'name' => 'purchase',
		'data' => array(
			'price' => '125.00',
			'product' => 'CT-Monthly-Basic',
		),
		'timestamp' => time(),
	));
	*/
	/*
	$send = cio_send_transactional_email(array(
		'transactional_message_id' => 2,
		'to' => 'dpetersson@gmail.com',
		'identifiers' => array(
			'id' => 123,
		),
		'message_data' => array(
			'first-name' => "Bob",
			'last-name' => "Dylan",
		),
	));
	
	print_r($send->meta->error);
	exit();
	*/
	return "";
}